blog/urls.py
from django.urls import path
from . import views
from .feeds import PostFeed

app_name = 'blog'

urlpatterns = [

    path('', views.home, name='home'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/tag/<str:tag_slug>/', views.post_list, name="posts_by_tag"),
    path("posts/<str:post_slug>/share/", views.post_share, name='post_share'),
    path('posts/<int:year>/<int:month>/<int:day>/<str:post_slug>/',
         views.post_details, name="post_details"),
    path('posts/edit/<int:id>/', views.edit, name='post_edit'),
    path('posts/delete/', views.delete, name='delete_post'),
    path('posts/<str:post_slug>/comments/',
         views.post_comment, name='post_comment'),

    path('feeds/', PostFeed(), name='post_feeds'),
    path('like-archive/', views.like_archive, name='like_archive'),
    path('check-auth/', views.check_auth, name='check_auth'),
    path('file_url_constructor/', views.file_url_constructor,
         name='file_url_constructor'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap, TagSiteMap


sitemaps = {
    'posts': PostSiteMap,
    'tags': TagSiteMap
}


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('account/', include('account.urls', namespace='account')),
    path('tinymce/', include("tinymce.urls")),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.conf import settings
from taggit.models import Tag
from .mytools import create_image_path
from django.urls import reverse

from tinymce.models import HTMLField
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        PUBLISHED = ('PB', "منتشر شده")
        DRAFT = ("DF", "در انتظار تایید")

    title = models.CharField("عنوان", max_length=255)

    slug = models.SlugField(
        max_length=255,
        unique_for_date='publish',
        allow_unicode=True,
        blank=True
    )

    description = models.TextField("توضیح مختصر")

    body = HTMLField('متن کامل')

    authors = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="posts"
    )

    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )

    tags = TaggableManager("تگ ها")

    photo = models.ImageField(
        upload_to=create_image_path,
        null=True,
        blank=True,
    )
    likes_count = models.PositiveIntegerField(default=0)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='posts_liked',
        blank=True
    )
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):

        return reverse("blog:post_details", args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])

    def generate_html_id(self):
        id = self.id * 10 - self.id * 3
        return id

    def save(self, *args, **kwargs):
        if not self.slug or self.slug != slugify(self.title):
            self.slug = slugify(self.title, allow_unicode=True)

        super().save(*args, **kwargs)


class Comment(models.Model):
    text = models.TextField("متن")
    author = models.CharField("نام", max_length=40)
    email = models.EmailField("آدرس ایمیل")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        related_name='comments'
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f"Wrote By {self.author} for {self.post}"

blog/forms.py
from django import forms
from .models import Comment, Post
from django.contrib.auth import get_user_model
from jalali_date.fields import SplitJalaliDateTimeField
from jalali_date.widgets import AdminSplitJalaliDateTime
from django.utils.safestring import mark_safe
from blog.widgets import CustomMedia, TinyMceWidget
import jdatetime
from django.utils.timezone import localtime
User = get_user_model()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'email',
            'text'
        ]


class PostShareForm(forms.Form):
    name = forms.CharField(label="نام فرستنده")
    from_email = forms.EmailField(label='ایمیل فرستنده')
    to_email = forms.EmailField(label='ایمیل گیرنده')
    extra_explanation = forms.CharField(
        widget=forms.Textarea,
        label="توضیحات اضافه",
        required=False
    )


class PostEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostEditForm, self).__init__(*args, **kwargs)
        self.fields['publish'] = SplitJalaliDateTimeField(
            widget=AdminSplitJalaliDateTime(),
        )

    body = forms.CharField(
        widget=TinyMceWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = "__all__"


class AdminPostEditForm(forms.ModelForm):
    body = forms.CharField(
        widget=TinyMceWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = "__all__"

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Comment
from blog.mytools import log_sql, create_image_path
from blog.forms import CommentForm, PostShareForm, PostEditForm

from account.models import Profile
from taggit.models import Tag

from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Prefetch
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponseNotFound
from django.conf import settings
import os
import json
import redis
from urllib.parse import urljoin
from utils.redis_client import redis_client as r
# Create your views here.
UserModel = get_user_model()


@require_POST
def file_url_constructor(request):

    if request.FILES.get('file'):
        try:
            file = request.FILES.get('file')
            post_id = request.POST.get('post_id')

            post = Post.published.get(id=post_id)

            raw_type = file.content_type
            file_type = 'video' if 'video' in raw_type else 'image'

            incomplete_path = create_image_path(
                post, file.name, file_type=file_type)

            # creating the file path using os library and create_image_path function (located on blog.mytools module)
            file_path = os.path.join(
                settings.MEDIA_ROOT, incomplete_path)

            # create directory for related post in order to store images related to it(if does not exists)
            os.makedirs(os.path.dirname(file_path), exist_ok=True)

            # use chunks() method of django UploadFile class and store image part by part on image_path
            with open(file_path, 'wb+') as path:
                for chunk in file.chunks():
                    path.write(chunk)

            # we used MEDIA_ROOT to store the image, but for return the url for this image, we must use MEDIA_URL
            file_url = urljoin(settings.MEDIA_URL, incomplete_path)
            print(file_url)
            return JsonResponse({'success': True, 'url': file_url})

        except Exception as e:
            print(e)
            return JsonResponse({'success': False, 'error': 'there is a problem'})


def home(request):

    return render(
        request,
        'home.html'
    )

# @permission_required


@permission_required('post.change_post', raise_exception=True)
@login_required
def edit(request, id):
    try:
        post = Post.objects.get(id=id)
    except Exception as e:
        return HttpResponseNotFound('There is a problem with retrive')

    form = PostEditForm(instance=post)

    if request.method == 'POST':

        form = PostEditForm(
            instance=post,
            data=request.POST,
            files=request.FILES
        )
        print(form)

        if form.is_valid():
            form.save()
            messages.success(
                request, 'پست مورد مورد نظر با موفقیت تغییر یافت!')
            print('====================================================')
            return redirect(post.get_absolute_url())
        print(form.errors)
    context = {
        'form': form,
        'post': post,
    }

    return render(
        request,
        'blog/edit.html',
        context
    )


@permission_required('post.delete_post', raise_exception=True)
@login_required
def delete(request):
    # this view will used for edit and delete the post
    if request.method == 'POST':
        post_id = request.POST.get('id')
        try:
            post = Post.published.get(id=post_id)
            post.delete()
            return JsonResponse({'status': 'ok', 'message': "پست مورد نظر با موفقیت حذف شد"})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': f'مشکلی رخ داده:\n{e}'})
    else:
        return JsonResponse({'error': 'Invalid request method'})


@log_sql
def post_list(request, tag_slug=None):

    all_posts = Post.published.prefetch_related(
        'tags', Prefetch(
            'authors',
            queryset=UserModel.objects.only('id', 'username', 'first_name')
        ),
        Prefetch(
            'archived_by',
            queryset=Profile.objects.only('id')
        )
    ).all()

    with_tag = None
    if tag_slug:
        print('tag')
        all_posts = all_posts.filter(tags__slug=tag_slug)
        with_tag = tag_slug

    paginator = Paginator(all_posts, 6, orphans=3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    # get the views related to each post from redis and couple the posts and their views together
    redis_view_keys = [f"post:{post.id}:view" for post in posts]
    views = [int(view) if view else 0 for view in r.mget(redis_view_keys)]
    posts_with_views = [{'post': post, 'view': view}
                        for post, view in zip(posts, views)]
    context = {
        "posts": posts_with_views,
        'tag': with_tag,
        'page': posts
    }
    return render(
        request,
        'blog/post_list.html',
        context
    )


@log_sql
def post_details(request, year, month, day, post_slug):
    post = Post.published.defer(
        'created',
        'status',
        'updated',
        'description'
    ).prefetch_related(
        Prefetch(
            'users_like',
            queryset=UserModel.objects.only('id')
        ),
        Prefetch(
            'authors',
            queryset=UserModel.objects.only('username', 'first_name')
        ),
        Prefetch(
            'comments',
            queryset=Comment.objects.defer(
                'updated', 'email', 'is_active').all()
        )
    ).get(
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=post_slug,
    )

    # increase the view of the post on redis database:
    views_count = r.incr(f'post:{post.id}:view')

    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'views_count': views_count
    }
    return render(
        request,
        'blog/post_details.html',
        context
    )


@login_required
def post_comment(request, post_slug):
    post = Post.published.get(slug=post_slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, 'نظر شما با موفقیت ثبت گردید.')
        else:
            message.error(
                request, 'مشکلی پیش آمده.لطفا مجددا نظر خود را ثبت کنید!')
    return redirect(post.get_absolute_url())


@login_required
def post_share(request, post_slug):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post_slug
    )

    form = PostShareForm()
    if request.method == "POST":
        form = PostShareForm(request.POST)
        if form.is_valid():
            post_url = request.build_absolute_uri(post.get_absolute_url())

            cd = form.cleaned_data
            name = cd.get('name')
            from_email = cd.get('from_email')
            to_email = cd.get('to_email')
            comment = cd.get('extra_explanation', '')

            subject = (
                f"پیام از طرف {name} ({from_email})"
            )
            message = (
                f"{name} پیشنهاد می کند که پست زیر را در وبسایت ما مطالعه کنید\n"
                f"اگر تمایل به خواندن این مطلب دارید،می توانید از لینکی که در زیر برایتان قرار داده شده به صفحه ی مربوط به این پست وارد شوید:\n\n"
                f"{post_url}\n\n"
                f"توضیخات {name}:{comment}"
            )
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[to_email],
            )
            messages.success(
                request, 'این پست با موفقیت برای فرد مورد نظر شما فرستاده شد.')
            return redirect(post.get_absolute_url())

    context = {
        'form': form,
    }
    return render(
        request,
        'blog/post_share.html',
        context
    )


@login_required
def like_archive(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')

    try:
        post = Post.published.get(id=post_id)

        if action == "like":
            post.users_like.add(request.user)
        elif action == 'unlike':
            post.users_like.remove(request.user)
        elif action == 'archive':
            request.user.profile.archived_posts.add(post)
        elif action == 'unarchive':
            request.user.profile.archived_posts.remove(post)
        elif action == 'add-to-read':
            request.user.profile.archived_posts.remove(post)
            request.user.profile.read_posts.add(post)
        else:
            request.user.profile.read_posts.remove(post)
        return JsonResponse({'status': 'ok'})
    except Post.DoesNotExist:
        pass
    return JsonResponse({"status": 'error'})


def check_auth(request):
    print(request.user.is_authenticated)
    return JsonResponse({'logged_in': request.user.is_authenticated})

templates/blog/edit.html
{% extends '_base.html' %}
{% load static %}


{% block title %}تغییر پست{% endblock title %}

{% block extra_head %}

{{ form.media }}

{% endblock extra_head %}

{% block content %}


<h4>از فرم زیر جهت اعمال تغییرات استفاده کنید:</h4>
<form class="form edit" action="{% url 'blog:post_edit' post.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="اعمال تغییرات">
</form>

<div id="staff-actions">
    <p><button class="action delete" data-id="{{ post.id }}">حذف</button></p>
</div>

<div id="confirmation">
    <!-- we will show confirmation message  to staff to  ensure about deletion of post -->
    <span>x</span>
    <p><strong></strong></p>
    <button id="confirm">Yes</button>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/delete_post.js' %}"></script>
<script src="{% static 'js/file_handler.js' %}"></script>
{% endblock %}

templates/blog/post_details.html
{% extends "_base.html" %}
{% load static %}
{% load jalali_tags %}
{% load blog_tags %}


{% block title %}جزئیات{% endblock title %}

{% block extra_head %}

{{ form.media }}
{% endblock extra_head %}

{% block content %}


<div id="post-{{ post.generate_html_id }}">
    <div class="post">
        <h1>{{ post.title }}</h1>
        <!-- date ================================================================================ -->
        <p><b>تاریخ انتشار:&nbsp;&nbsp;</b>
            {{ post.publish | to_jalali:"%Y/%m/%d _ %H:%M" | farsi_num }}
        </p>

        <!-- authors ================================================================================ -->
        <p><b>نویسنده/نویسندگان:&nbsp;</b>
            {% for author in post.authors.all %}
            <b>{{ author.first_name | default:author.username }}</b>{% if not forloop.last %}<b>،&nbsp;</b>{% endif %}
            {% endfor %}
        </p>

        <!-- body ================================================================================ -->
        <p class="just">
            {{ post.body | safe }}
        </p>
    </div>

    <!-- post share link  ================================================================================ -->
    <p><b><a href="{% url 'blog:post_share' post.slug %}">اشتراک گذاری</a>&nbsp;&nbsp;&larr;</b></p>

    <!-- tags ================================================================================ -->
    <p><b>تگ:</b>&nbsp;&nbsp;
        {% with post.tags.all as tags %}
        {% for tag in tags %}
        <strong><a href="{% url 'blog:posts_by_tag' tag.slug %}">{{ tag }}</a></strong>&nbsp;&nbsp;
        {% endfor %}
        {% endwith %}
    </p>
    <!-- liked, seen, archived -->
    <div class="post-footer">
        <!-- like section -->
        <span class="like-container">
            {% with users_liked=post.users_like.all %}
            <!-- will use below anchor tag to send information related to like and unlike the post -->
            <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_liked %}un{% endif %}like"
                data-url="{% url 'blog:like_archive' %}" data-limg='{% static "blog_photo/like.png" %}'
                data-unlimg="{% static 'blog_photo/unlike.png' %}" class="like">

                {% if user in users_liked %}
                <img src="{% static 'blog_photo/like.png' %}" alt="like" width="20">
                {% else %}
                <img src="{% static 'blog_photo/unlike.png' %}" alt="unlike" width="20">
                {% endif %}

            </a>
            <span class="total">{{ users_liked.count }}</span>
            {% endwith %}
        </span>&nbsp;&nbsp;

        <!-- archive section -->
        {% include 'bases/archive.html' with post=post %}

        <!-- views count -->
        {% include "bases/view_count.html" with views_count=views_count %}
    </div>

    {% if request.user.is_staff and request.user in post.authors.all %}
    <div id="staff-actions">
        <p><button class="action delete" data-id="{{ post.id }}"
                data-targetid="{{ post.generate_html_id }}">حذف</button></p>
        <p><a href="{% url 'blog:post_edit' id=post.id %}">ویرایش</a></p>
    </div>
    {% endif %}

    <div>

    </div>
    <!-- comments ================================================================================ -->
    <div class="comments">
        {% with post.comments.all as comments %}
        <h2>نظرات:</h2>
        <p>تعداد نظرات ثبت شده:&nbsp;&nbsp;<strong>{{ comments.count }}&nbsp;نظر</strong></p>
        {% for comment in comments %}
        <dl>
            <dt>توسط&nbsp;<strong>{{ comment.author }}</strong>&nbsp; در تاریخ&nbsp;&nbsp;
                {{ comment.created | to_jalali:"%Y/%m/%d _ %H:%M" |farsi_num }}
            </dt>
            <dd>
                {{ comment.text }}
            </dd>
        </dl>
        {% empty %}
        <p>فعلا نظری ثبت نشده!</p>
        {% endfor %}

        <!-- comment form ===============================================================================  -->
        <div>
            <h2>ثبت نظر:</h2>
            {% if comments %}
            <p>با ثبت نظر در خصوص این مطلب ما را در بهبود کیفت مطالب یاری کنید.</p>
            {% else %}
            <p>اولین نظر را شما ثبت کنید.</p>
            {% endif %}

            {% include 'bases/comment_form.html' with form=form post_slug=post.slug %}
        </div>


        {% endwith %}
    </div>

</div>

<div id="confirmation">
    <!-- we will show confirmation message  to staff to  ensure about deletion of post -->
    <span>x</span>
    <p><strong></strong></p>
    <button id="confirm">Yes</button>

</div>

{% endblock content %}



{% block script %}
<script src="{% static 'js/delete_post.js' %}"></script>
{% endblock script %}

templates/blog/post_list.html
{% extends "_base.html" %}
{% load static %}
{% load jalali_tags %}
{% load blog_tags %}
{% block title %}{{ "پست ها" | nospace}} و مقالات{% endblock title %}

{% block content %}
{% if tag %}
<h1>{{ "پست های" | nospace }} منتشر شده با موضوع "{{ tag }}":</h1>
{% else %}

<h1>{{ "پست های" | nospace }} منتشر شده:</h1>
{% endif %}
{% for cpost in posts %}

{% with cpost.post as post %}
<div id="post-{{ post.generate_html_id }}">
    <!-- title================================================================================================= -->
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

    <!-- date ================================================================================================= -->
    <p>منتشر شده در تاریخ {{ post.publish | to_jalali:'%Y/%m/%d _ %H:%M' | farsi_num }}&nbsp;&nbsp;
        توسط&nbsp;&nbsp;&nbsp;
        {% for author in post.authors.all %}
        {{ author.name | default:author.username }}{% if not forloop.last %}<b>،&nbsp;</b>{% endif %}
        {% endfor %}
    </p>

    <!-- body ================================================================================================= -->
    <p class="just">{{ post.description | linebreaks }}</p>

    <p><strong><a href="{{ post.get_absolute_url }}">ادامه پست...</a></strong></p>
    <!-- tags================================================================================================= -->
    {% with post.tags.all as tags %}
    {% if tags %}
    <p>
        {% for tag in tags %}
        <a href="{% url 'blog:posts_by_tag' tag.slug %}"><strong>{{ tag }}</strong></a>
        {% if not forloop.last %}<b>،</b>{% endif %}
        {% endfor %}
    </p>
    {% endif %}
    {% endwith %}
    <!-- post footer (liked, seen) ================================================================================ -->
    <div>

        <span>
            <span>{{ likes_count }}</span>
            <span><img src="{% static 'blog_photo/like.png' %}" alt="liked" width="20px"></span>
        </span>

        <!-- archive section ====================================================================================== -->

        {% include 'bases/archive.html' with post=post %}

        <!-- view count section ==================================================================================== -->
        {% include 'bases/view_count.html' with views_count=cpost.view %}
    </div>
    {% if request.user.is_staff and request.user in post.authors.all %}
    <div id="staff-actions">
        <p><button class="action delete" data-id="{{ post.id }}"
                data-targetId="{{ post.generate_html_id }}">حذف</button></p>
        <p><a href="{% url 'blog:post_edit' id=post.id %}">ویرایش</a></p>
    </div>
    {% endif %}


</div>
{% endwith %}


{% empty %}
<p><strong>فعلا پستی منتشر نشده!</strong></p>
{% endfor %}

<!-- pagination ========================================================================================== -->
{% if page.paginator.num_pages != 1 %}
{% include 'bases/pagination.html' with page=page %}
{% endif %}

<div id="confirmation">
    <!-- we will show confirmation message  to staff to  ensure about deletion of post -->
    <span>x</span>
    <p><strong></strong></p>
    <button id="confirm">Yes</button>
</div>
{% endblock content %}
<!-- delete and edit post using js -->
{% block script %}
<script src="{% static 'js/delete_post.js' %}"></script>
{% endblock script %}

templates/blog/post_share.html
{% extends "_base.html" %}

{% block title %}اشتراک گذاری{% endblock title %}

{% block content %}

<h1>از فرم زیر جهت اشتراک گذاری استفاده کنید:</h1>
<div>
    <form class="form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="post_slug" value="{{ post_slug }}">
        <input type="submit" value="اشتراک گذاری">
    </form>
</div>
{% endblock content %}