blog/urls.py
from django.urls import path
from . import views
from .feeds import PostFeed

app_name = 'blog'

urlpatterns = [

    path('', views.home, name='home'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/tag/<str:tag_slug>/', views.post_list, name="posts_by_tag"),
    path("posts/<str:post_slug>/share/", views.post_share, name='post_share'),
    path('posts/<int:year>/<int:month>/<int:day>/<str:post_slug>/',
         views.post_details, name="post_details"),
    path('posts/edit/<int:id>/', views.edit, name='post_edit'),
    path('posts/delete/', views.delete, name='delete_post'),
    path('posts/<str:post_slug>/comments/',
         views.post_comment, name='post_comment'),

    path('feeds/', PostFeed(), name='post_feeds'),
    path('like-archive/', views.like_archive, name='like_archive'),
    path('check-auth/', views.check_auth, name='check_auth'),
    path('file_url_constructor/', views.file_url_constructor,
         name='file_url_constructor'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap, TagSiteMap


sitemaps = {
    'posts': PostSiteMap,
    'tags': TagSiteMap
}


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('account/', include('account.urls', namespace='account')),
    path('tinymce/', include("tinymce.urls")),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

templates/bases/archive.html
{% load static %}
<span class="archive-container">
    {% with archived_by=post.archived_by.all %}
    <a href="#" data-id="{{ post.id }}" data-action="{% if user.profile in archived_by %}un{% endif %}archive"
        data-url="{% url 'blog:like_archive' %}" data-archimg="{% static 'blog_photo/archived.png' %}"
        data-unarchimg="{% static 'blog_photo/unarchived.png' %}" class="archive">

        {% if user.profile in archived_by %}
        <img src="{% static 'blog_photo/archived.png' %}" alt="archive" width="20">
        {% else %}
        <img src="{% static 'blog_photo/unarchived.png' %}" alt="unarchive" width="20">
        {% endif %}
    </a>
    {% endwith %}
</span>

templates/bases/comment_form.html
<div class="comment-form">
    <form action="{% url 'blog:post_comment' post_slug %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ثبت نظر">
    </form>
</div>

templates/bases/pagination.html
<div class="pagination">
    {% if page.has_previous %}
    صفحه ی <strong><a href="?page={{ page.previous_page_number }}">قبلی</a></strong>&nbsp;&nbsp;|
    {% endif %}
    <strong>صفحه ی {{ page.number }} از {{ page.paginator.num_pages }}</strong>&nbsp;&nbsp; |
    {% if page.has_next %}
    صفحه ی <strong><a href="?page={{ page.next_page_number }}">بعدی</a></strong>
    {% endif %}
</div>

templates/bases/view_count.html
{% load static %}
<span class="views-count">
    <img src="{% static 'blog_photo/view-icon.png' %}" alt="views" width="20">
    <span>{{ views_count }}</span>
</span>