account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('dashboard/<str:section>/', views.dashboard, name='dashboard'),
    path('dashboard/edit/info/', views.apply_user_edit, name='apply_user_edit'),
    path('dashboard/admin/<str:section>/',
         views.admin_dashboard, name='admin_dashboard')
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import PostFeed

app_name = 'blog'

urlpatterns = [

    path('', views.home, name='home'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/tag/<str:tag_slug>/', views.post_list, name="posts_by_tag"),
    path("posts/<str:post_slug>/share/", views.post_share, name='post_share'),
    path('posts/<int:year>/<int:month>/<int:day>/<str:post_slug>/',
         views.post_details, name="post_details"),
    path('posts/edit/<int:id>/', views.edit, name='post_edit'),
    path('posts/delete/', views.delete, name='delete_post'),
    path('posts/<str:post_slug>/comments/',
         views.post_comment, name='post_comment'),

    path('feeds/', PostFeed(), name='post_feeds'),
    path('like-archive/', views.like_archive, name='like_archive'),
    path('check-auth/', views.check_auth, name='check_auth'),
    path('file_url_constructor/', views.file_url_constructor,
         name='file_url_constructor'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap, TagSiteMap


sitemaps = {
    'posts': PostSiteMap,
    'tags': TagSiteMap
}


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('account/', include('account.urls', namespace='account')),
    path('tinymce/', include("tinymce.urls")),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

templates/_base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
    {% block extra_head %}
    {% endblock extra_head %}
</head>

<body>
    <div>
        <ul class="nav">
            <li><a href="{% url 'blog:home' %}">صفحه ی اصلی</a></li>
            <li><a href="{% url 'blog:post_list' %}">{{ "پست ها"| nospace }} و مقالات</a></li>
            <li>همچنین از<a href="{% url 'blog:post_feeds' %}">فیدهای</a> ما استفاده کنید</li>
            {% if request.user.is_authenticated %}
            <li>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <input class="bare-btn" type="submit" value="خروج">
                </form>
            </li>
            <li><a href="{% url 'account:dashboard' 'info' %}">داشبورد</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">ورود</a></li>
            <li><a href="{% url 'account:signup' %}">ایجاد حساب</a></li>
            {% endif %}
        </ul>
    </div>
    <hr>
    <!-- all template inheriting form this template, then I defined just below lines for displaying messages -->
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class='{{ message.tags }}' {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <!-- contents ============================================================================ -->
    {% block content %}
    {% endblock content %}

    <script src="{% static 'js/asin_script.js' %}"></script>
    {% block script %}
    {% endblock script %}
</body>

</html>

templates/home.html
{% extends "_base.html" %}


{% block title %}صفحه ی اصلی{% endblock title %}

{% block content %}
<h1>Hello</h1>
{% endblock content %}